services:
  mysql-db:
    image: mysql:latest
    container_name: MySQLdb
    volumes:
      - mysql_data:/var/lib/mysqlRestobar
    restart: unless-stopped
    env_file: .env
    ports:
      - "3312:3312"
    networks:
      - Projectrestobar

  backend:
    build: .
    container_name: DjangoCont
    env_file: .env
    restart: always
    volumes:
      - .:/appDocker
    depends_on:
      - mysql-db
    expose:
      - 8000
    ports:
      - "8000:8000"
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    networks:
      - Projectrestobar

volumes:
  mysql_data:
    