# Generated by Django 4.1.3 on 2022-11-28 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_rut', models.CharField(db_column='ADMIN_RUT', max_length=13, primary_key=True, serialize=False)),
                ('admin_mombre', models.CharField(blank=True, db_column='ADMIN_MOMBRE', max_length=50, null=True)),
                ('admin_pass', models.CharField(blank=True, db_column='ADMIN_PASS', max_length=100, null=True)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('banco_id', models.IntegerField(db_column='BANCO_ID', primary_key=True, serialize=False)),
                ('banco_nombre', models.CharField(blank=True, db_column='BANCO_NOMBRE', max_length=100, null=True)),
            ],
            options={
                'db_table': 'banco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cli_rut', models.CharField(db_column='CLI_RUT', max_length=13, primary_key=True, serialize=False)),
                ('cli_nombre', models.CharField(blank=True, db_column='CLI_NOMBRE', max_length=50, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('com_id', models.IntegerField(db_column='COM_ID', primary_key=True, serialize=False)),
                ('com_fecha_hora', models.DateTimeField(blank=True, db_column='COM_FECHA_HORA', null=True)),
                ('com_nro_personas', models.IntegerField(blank=True, db_column='COM_NRO_PERSONAS', null=True)),
            ],
            options={
                'db_table': 'comanda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Garzon',
            fields=[
                ('gar_rut', models.CharField(db_column='GAR_RUT', max_length=13, primary_key=True, serialize=False)),
                ('gar_nombre', models.CharField(blank=True, db_column='GAR_NOMBRE', max_length=50, null=True)),
            ],
            options={
                'db_table': 'garzon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('mesa_id', models.IntegerField(db_column='MESA_ID', primary_key=True, serialize=False)),
                ('mesa_nombre', models.CharField(blank=True, db_column='MESA_NOMBRE', max_length=100, null=True)),
            ],
            options={
                'db_table': 'mesa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('of_id', models.IntegerField(db_column='OF_ID', primary_key=True, serialize=False)),
                ('of_finicio', models.DateField(blank=True, db_column='OF_FINICIO', null=True)),
                ('of_ffin', models.DateField(blank=True, db_column='OF_FFIN', null=True)),
                ('of_precio', models.IntegerField(blank=True, db_column='OF_PRECIO', null=True)),
            ],
            options={
                'db_table': 'oferta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('pago_id', models.IntegerField(db_column='PAGO_ID', primary_key=True, serialize=False)),
                ('pago_fecha_hora', models.DateTimeField(blank=True, db_column='PAGO_FECHA_HORA', null=True)),
                ('pago_nro_boucher', models.CharField(blank=True, db_column='PAGO_NRO_BOUCHER', max_length=100, null=True)),
                ('pago_monto', models.IntegerField(blank=True, db_column='PAGO_MONTO', null=True)),
            ],
            options={
                'db_table': 'pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('prod_id', models.IntegerField(db_column='PROD_ID', primary_key=True, serialize=False)),
                ('prod_nombre', models.CharField(blank=True, db_column='PROD_NOMBRE', max_length=50, null=True)),
                ('prod_precio', models.IntegerField(blank=True, db_column='PROD_PRECIO', null=True)),
                ('prod_disponible', models.IntegerField(blank=True, db_column='PROD_DISPONIBLE', null=True)),
                ('prod_fecha_ingreso', models.DateField(blank=True, db_column='PROD_FECHA_INGRESO', null=True)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('tpag_id', models.IntegerField(db_column='TPAG_ID', primary_key=True, serialize=False)),
                ('tpag_nombre', models.CharField(blank=True, db_column='TPAG_NOMBRE', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tipo_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoProd',
            fields=[
                ('tp_id', models.IntegerField(db_column='TP_ID', primary_key=True, serialize=False)),
                ('tp_nombre', models.CharField(blank=True, db_column='TP_NOMBRE', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tipo_prod',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('ven_id', models.IntegerField(db_column='VEN_ID', primary_key=True, serialize=False)),
                ('ven_fecha', models.DateField(blank=True, db_column='VEN_FECHA', null=True)),
            ],
            options={
                'db_table': 'venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComOf',
            fields=[
                ('com', models.OneToOneField(db_column='COM_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='data.comanda')),
                ('com_of_cantidad', models.IntegerField(blank=True, db_column='COM_OF_CANTIDAD', null=True)),
                ('com_of_precio', models.IntegerField(blank=True, db_column='COM_OF_PRECIO', null=True)),
            ],
            options={
                'db_table': 'com_of',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComProd',
            fields=[
                ('com', models.OneToOneField(db_column='COM_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='data.comanda')),
                ('cp_cantidad', models.IntegerField(blank=True, db_column='CP_CANTIDAD', null=True)),
                ('cp_precio', models.IntegerField(blank=True, db_column='CP_PRECIO', null=True)),
            ],
            options={
                'db_table': 'com_prod',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProdOferta',
            fields=[
                ('prod', models.OneToOneField(db_column='PROD_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='data.producto')),
            ],
            options={
                'db_table': 'prod_oferta',
                'managed': False,
            },
        ),
    ]
