# Generated by Django 4.1.3 on 2022-12-08 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComOf',
        ),
    ]
