# Generated by Django 4.1.3 on 2022-12-11 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_delete_comof'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComOf',
            fields=[
                ('com', models.OneToOneField(db_column='COM_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='data.comanda')),
                ('com_of_cantidad', models.IntegerField(blank=True, db_column='COM_OF_CANTIDAD', null=True)),
                ('com_of_precio', models.IntegerField(blank=True, db_column='COM_OF_PRECIO', null=True)),
            ],
            options={
                'db_table': 'com_of',
                'managed': False,
            },
        ),
    ]
